---
- name: Ensure country code is set
  ansible.builtin.lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    line: 'country=US'
    owner: root
    mode: 0644
    create: true
    state: present

- name: Generates encoded wpa passphrase
  ansible.builtin.shell:
    cmd: wpa_passphrase {{ wan_ssid }} {{ wan_pass_phrase }}
  args:
    executable: /bin/bash
  register: passphrase
  changed_when: (passphrase.stdout)

- name: Ensure wifi network info is up to date
  ansible.builtin.replace:
    path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    regexp: 'network=\{\s*ssid="{{ wan_ssid }}"\s*.*?\s*\}'
    replace: "{{ passphrase.stdout }}"
  register: wlan_info

- name: Ensure wifi network info exists in wlan0 config
  ansible.builtin.lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    line: '{{ passphrase.stdout }}'
    state: present
  when: (wlan_info.changed == false)

- name: Ensure clear text passphrase is absent
  ansible.builtin.lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    regexp: '{{ wan_pass_phrase }}'
    state: absent

- name: Ensure wpa_supplicant.conf country code is set
  ansible.builtin.lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    line: 'country=US'
    owner: root
    mode: 0644
    create: true
    state: present
